import type { NextPage } from "next";
import Head from "next/head";
import { Button, Switch, Text, useTheme } from "@nextui-org/react";
import { useTheme as useNextTheme } from "next-themes";
import NavBar from "../src/Components/NavBar";

const Home: NextPage = () => {
   const { setTheme } = useNextTheme();
   const { isDark, type, theme } = useTheme();
   return (
      <div>
         <Head>
            <title>Full NextJs Ecommerce</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main>
            <NavBar />
         </main>
      </div>
   );
};

export default Home;
